name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
  COVERAGE_MIN: "80"
  P95_MS_ALLOCATIONS: "200"

jobs:
  core-tests:  # alias: core
    if: github.event_name == 'pull_request'
    name: Core Tests and Coverage
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4
      - name: تنظیم پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: نصب وابستگی ها
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
      - name: اجرای آزمون های هسته ای
        run: |
          PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -p pytest_cov --cov=src --cov-report=xml --cov-fail-under=${{ env.COVERAGE_MIN }} -m "not golden and not e2e and not smoke" tests
      - name: بارگذاری گزارش پوشش
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: warn

  golden-determinism:  # alias: exporter-golden
    if: github.event_name == 'pull_request'
    name: Golden Exporter Determinism
    runs-on: ubuntu-latest
    needs: core-tests
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4
      - name: تنظیم پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: نصب وابستگی ها
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
      - name: اجرای آزمون های طلایی صادرکننده
        run: |
          PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -m golden tests/test_exporter_golden.py
      - name: بارگذاری نمونه های طلایی
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: golden-snapshots
          path: tests/golden
          if-no-files-found: warn

  smoke-e2e:
    if: github.event_name == 'push'
    name: Smoke & E2E
    runs-on: ubuntu-latest
    steps:
      - name: دریافت کد
        uses: actions/checkout@v4
      - name: تنظیم پایتون
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: نصب وابستگی ها
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then python -m pip install -r requirements-dev.txt; fi
      - name: اجرای دود و مسیر شاد
        run: |
          PYTEST_DISABLE_PLUGIN_AUTOLOAD=1 pytest -m "smoke and e2e" -q
